name: Weekly Dependency Update

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install pnpm
        run: npm i -g pnpm  
      - name: Install dependencies
        run: pnpm i
      - name: Update dependencies
        run: pnpm update --latest
      - name: Commit and push
        run: |
          git config --global user.name 'Junseong Park'
          git config --global user.email 'junseongpark.dev@gmail.com'
          git add .
          git commit -m "chore(deps): weekly dependencies update from Github Actions"
          git push origin main
